apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: appscode
  name: appscode
  namespace: appscode
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: appscode
status:
  loadBalancer: {}
