apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim2
  namespace: database
spec:
  storageClassName: standard2
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
